import { Injectable, computed, signal } from '@angular/core';
import {
  CreateGcashTransactionRequest,
  CreateLoadTransactionRequest,
  CreateSaleRequest,
  GcashTransaction,
  LoadTransaction,
  Sale,
} from '../models';

/**
 * Common fields for every queued mutation. `clientRef` is the queue
 * key — generated by the producer (SaleService) so subsequent retries
 * and dedupe lookups can find the same entry. `attempts` + `lastError`
 * are surfaced by the UI ("Retry sync" pill, dialog with failed items).
 */
interface QueuedBase {
  readonly clientRef: string;
  readonly enqueuedAt: string;
  attempts: number;
  lastError?: string;
}

/**
 * A sale that was rung up while offline and is waiting to be replayed.
 * `optimistic` is the locally-synthesized Sale shown to the cashier in
 * the meantime — on successful replay it's swapped for the backend's
 * canonical record (matching ids).
 */
export interface QueuedSale extends QueuedBase {
  readonly kind: 'sale';
  readonly request: CreateSaleRequest;
  readonly optimistic: Sale;
}

/**
 * A refund issued while offline. The cashier's transaction list shows
 * the targeted sale as REFUNDED immediately; the backend POST is
 * deferred until the network returns. A 409 "already refunded" on
 * replay is treated as success (idempotent).
 */
export interface QueuedRefund extends QueuedBase {
  readonly kind: 'refund';
  readonly saleId: string;
  readonly reason: string | null;
}

/**
 * A GCash transaction rung up while offline. `optimistic` is the locally
 * synthesized row shown on the receipt and in My Transactions until the
 * backend's canonical record replaces it on replay.
 */
export interface QueuedGcash extends QueuedBase {
  readonly kind: 'gcash';
  readonly request: CreateGcashTransactionRequest;
  readonly optimistic: GcashTransaction;
}

/** A cellphone-load transaction rung up while offline. Same shape as the
 *  GCash entry. */
export interface QueuedLoad extends QueuedBase {
  readonly kind: 'load';
  readonly request: CreateLoadTransactionRequest;
  readonly optimistic: LoadTransaction;
}

export type QueuedMutation = QueuedSale | QueuedRefund | QueuedGcash | QueuedLoad;

const STORAGE_KEY = 'maxpos.offline.sale-queue.v1';

/**
 * Persisted FIFO queue of mutations that haven't reached the backend
 * yet — sales (creates) and refunds.
 *
 * Backed by localStorage because:
 *   - it's synchronous (no Promise ceremony in the hot path of checkout),
 *   - the payload per entry is ~1-2 KB and a cashier's offline window is
 *     capped by the JWT TTL (8h default) — well under the 5-10 MB quota,
 *   - IndexedDB adds a dependency + async everywhere for no practical win
 *     at this scale. Can be swapped later without API changes.
 */
@Injectable({ providedIn: 'root' })
export class OfflineQueueService {
  private readonly _queue = signal<QueuedMutation[]>(this.readFromStorage());

  readonly queue = this._queue.asReadonly();
  readonly pendingCount = computed(() => this._queue().length);
  readonly hasPending = computed(() => this._queue().length > 0);
  readonly pendingSales = computed(
    () => this._queue().filter((q): q is QueuedSale => q.kind === 'sale').length,
  );
  readonly pendingRefunds = computed(
    () => this._queue().filter((q): q is QueuedRefund => q.kind === 'refund').length,
  );
  readonly pendingGcash = computed(
    () => this._queue().filter((q): q is QueuedGcash => q.kind === 'gcash').length,
  );
  readonly pendingLoad = computed(
    () => this._queue().filter((q): q is QueuedLoad => q.kind === 'load').length,
  );

  /** Push a new mutation to the back of the queue and persist. */
  enqueue(entry: QueuedMutation): void {
    this._queue.update((list) => {
      const next = [...list, entry];
      this.writeToStorage(next);
      return next;
    });
  }

  /** Drop a queued entry by its clientRef — use after a successful replay. */
  remove(clientRef: string): void {
    this._queue.update((list) => {
      const next = list.filter((q) => q.clientRef !== clientRef);
      this.writeToStorage(next);
      return next;
    });
  }

  /** Bump attempts + record the error so the UI can surface failing entries. */
  markAttempted(clientRef: string, error?: string): void {
    this._queue.update((list) => {
      const next = list.map((q) =>
        q.clientRef === clientRef
          ? { ...q, attempts: q.attempts + 1, lastError: error }
          : q,
      );
      this.writeToStorage(next);
      return next;
    });
  }

  /** FIFO snapshot for the sync runner. */
  peekAll(): readonly QueuedMutation[] {
    return this._queue();
  }

  /** Nuke the queue (used on sign-out so a different cashier doesn't inherit it). */
  clear(): void {
    this._queue.set([]);
    this.writeToStorage([]);
  }

  private readFromStorage(): QueuedMutation[] {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) return [];
      const parsed = JSON.parse(raw) as Array<Partial<QueuedMutation> & QueuedBase>;
      if (!Array.isArray(parsed)) return [];
      // Legacy entries (pre-refund support) have no `kind` field — they
      // were always sales. Backfill the discriminator on read so the
      // dispatch in OfflineSyncService doesn't need a null check.
      return parsed.map((entry) =>
        ('kind' in entry && entry.kind ? entry : { ...entry, kind: 'sale' }) as QueuedMutation,
      );
    } catch {
      // Corrupted storage — safer to discard than to keep replaying bad data.
      localStorage.removeItem(STORAGE_KEY);
      return [];
    }
  }

  private writeToStorage(entries: readonly QueuedMutation[]): void {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(entries));
    } catch {
      /* Quota exceeded / SecurityError (private mode) — silent. Worst case
         the queue becomes memory-only and is lost on reload. */
    }
  }
}
