-- ─────────────────────────────────────────────────────────────────────────
-- Multi-store — Phase 5: let store_settings.id auto-allocate.
--
-- store_settings.id was a hardcoded singleton (id = 1; the V1 CHECK(id=1)
-- was dropped in V34). For multiple stores each needs its own settings row
-- with a distinct id, so make the column an identity. The existing row
-- keeps id = 1; the identity sequence is advanced past it so new stores
-- get 2, 3, … Settings are now looked up per store (the row for the current
-- tenant), not by id = 1.
-- ─────────────────────────────────────────────────────────────────────────

ALTER TABLE store_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Existing row is id = 1; start the sequence after the current max so a new
-- store's settings can't collide with it.
SELECT setval(pg_get_serial_sequence('store_settings', 'id'),
              (SELECT COALESCE(MAX(id), 1) FROM store_settings));
