-- ─────────────────────────────────────────────────────────────────────────
-- Multi-store — platform settings (singleton).
--
-- Platform-level (non-tenant) configuration owned by the super admin. Holds
-- the default currency applied to new store registrations and used to format
-- aggregated revenue in the platform console. Single-row table.
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE platform_settings (
    id                       INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    default_currency         VARCHAR(8)  NOT NULL DEFAULT 'USD',
    default_currency_symbol  VARCHAR(8)  NOT NULL DEFAULT '$',
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO platform_settings (default_currency, default_currency_symbol)
VALUES ('USD', '$');
